### PR TITLE
Add Scaleway S3 provider

### PR DESCRIPTION
**Pull request by mkll**

### CODE REVIEW

**Review by tib — COMMENTED** [review]
I'm not familiar with Scaleway S3, but the changes look good. Quick question: is the credentials the same for AWS & Scaleway? Is the credentials provider going to work for both services? If the answer is yes, then I suppose we can merge this PR. 

Thank you for the contribution. 👍

**Comment by mkll** [comment]
@tib S3 implementation in Scaleway mostly "standard", so `s3cmd` and other S3 CLI utilities works out of the box. As for PR, this code is working in my project right now:

```swift
app.fileStorages.use(.scalewayS3(credentialProvider: <credential>,
                                 region: .other("nl-ams"),
                                 bucket: "smartload-photos"), as: .scaleway)
```

Note. AWS regions come from Soto, so I haven't found a way to include Scaleway S3 regions in the enum. But that doesn't seem like a big problem.

s3cmd output:
```
~$ s3cmd ls s3://smartload-photos
2021-05-16 14:02       186127  s3://smartload-photos/1a7a26cb8d7542f99cfccd91247769da.png
```

**Comment by mkll** [comment]
Thank you for this amazing library!

**Comment by mkll** [comment]
P.S. DigitalOcean S3 implementation is on the way. :)

**Comment by tib** [comment]
Sounds really good, I just merged the code, will create a new release later on today. Thanks again. :)

**Pull request merged**
